### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by SimonAKing** [IceHe/lib#1]
一小时前在 `Github` 上搜索技术教程 ，又无意间跳转到了您的仓库，

然后，我看了很久的 `lifelogs` ，以及博客空间等很多博文,令我非常震撼。

您的 `lifelogs`纪录 表示出对时间的苛刻 、对自己的要求，这让我非常的佩服，愧疚。

并且，您对人生的总结，给我留下了一个很立体的形象  。

......

想说些什么，又不知道说什么 😄 

我祝您 2019年 身体健康，技术热情继续高涨！

**Comment by IceHe** [comment]
@Tomotoes 很惭愧，我不过是嘴强王者，还要多加努力。

**Comment by SimonAKing** [comment]
嗯嗯 , 加油~

**Comment by IceHe** [comment]
@Tomotoes 可以加个微信交个朋友~ IceHooo
