### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [IceHe/lib#4]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`cli.md`](https://github.com/IceHe/lib/blob/e0319e11bf8b1abaf56ff46828fbdbd768b75f94/marks/tools/cli.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by IceHe** [comment]
> Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`cli.md`](https://github.com/IceHe/lib/blob/e0319e11bf8b1abaf56ff46828fbdbd768b75f94/marks/tools/cli.md). This domain expired a few years ago and is not controlled by Homebrew anymore.
> 
> When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.
> 
> Thank you,
> the Homebrew team.

I have updated the related links in cli.md.
Thanks for your feedback~
