### ISSUE TITLE
23333

### ISSUE THREAD

**Issue by itcuihao** [IceHe/lib#5]
https://icehe.xyz/#/past/2018-spring-to-2019-autumn 加油加油，昨天打开博客没有关闭，今天刷新看到这个，养成好的习惯是最难的，只能说加油加油

**Comment by IceHe** [comment]
> https://icehe.xyz/#/past/2018-spring-to-2019-autumn 加油加油，昨天打开博客没有关闭，今天刷新看到这个，养成好的习惯是最难的，只能说加油加油

@itcuihao 谢谢~
